### ISSUE TITLE
Multi camera view

### ISSUE THREAD

**Issue by Zurlon** [dfaour/downloadPanopto#2]
For a video with 3 camera sources, your script links the mp4 with the first 2 camera sources joined together. I can find this easily by ctrl+f in the page code. But for a video with 3 sources, is there a way to download the third source, and ideally the first two sources separately? I've poked around a bit and I can find the the 2 different HLS files coming through but I don't know how to turn that into a working url.

**Comment by dfaour** [comment]
Unfortunately, I am not sure how the third camera source factors in to this! I don't have access to any 3-source videos to poke around at it, either. I'm sorry about that - wish I could be of more help. If you are able to get something working, please let me know!
