### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by SgtBlade** [dfaour/downloadPanopto#3]
Hi, the video quality of the file you download does not seem to be the same as the one you see on panopto. Do you know if there's a way to access it? The video on panopto is +/- 1080p while the downloaded video is 540p

**Comment by dfaour** [comment]
Hi, unfortunately I don't think there is any way to correct this. This tool detects videos that are pre-made and available on the server. If the server doesn't have a higher quality version available, you'll have to look for another way to get the video. Sorry! Good luck!
